
### Create Game
POST http://localhost:8080/v1/games HTTP/1.1
content-type: application/json

{
    "user1": "Alex",
    "user2": "Sam",
    "GameMode": 0
}

### Get Games
GET http://localhost:8080/v1/games HTTP/1.1
###

@gameid = a9bb4175-9a91-4240-bb79-cf3d7c1989e8

### Get Game Status
GET http://localhost:8080/v1/games/{{gameid}} HTTP/1.1

### Create Move
@x = 2
@y = 0
@move = X
# POST http://localhost:8080/v1/games/{{gameid}}/{{x}}/{{y}}/{{move}} HTTP/1.1
POST http://localhost:8080/v1/games/{{gameid}}/move HTTP/1.1
content-type: application/json

{
    "X": 1,
    "Y": 0,
    "Move": "X"
}

###